apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: integration-example
spec:
  tasks:
  - name: export-npmlib
    taskRef:
      name: npm-export
    params:
    - name: directory
      #value: integration-example/nodelib
      # With local git we're only pushing the project folder
      value: nodelib
  - name: export-npmlib2
    taskRef:
      name: npm-export
    params:
    - name: directory
      value: libsfolder/nodelib2
  - name: build-nodefrontend
    taskRef:
      name: caching-kaniko
    params:
    - name: pathToDockerFile
      value: /workspace/nodefrontend/Dockerfile
    - name: pathToContext
      value: /workspace/nodefrontend
  - name: itest-nodefrontend
    taskRef:
      name: test-completion
    params: []
