apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: integration-example-1
spec:
  pipelineRef:
    name: integration-example
  triggerRef:
    type: manual
  serviceAccount: 'default'
  results:
    type: 'gcs'
    url: 'gcs://somebucket/results/logs'
  resources:
  - name: export-npmlib
    inputs:
    - name: workspace
      resourceRef:
        name: integration-example-git
    outputs:
    - name: builtImage
      resourceRef: 
        name: integration-example-npmlib-image
  - name: export-npmlib2
    inputs:
    - name: workspace
      resourceRef:
        name: integration-example-git
    outputs:
    - name: builtImage
      resourceRef:
        name: integration-example-npmlib2-image
  - name: build-nodefrontend
    inputs:
    - name: workspace
      resourceRef:
        name: integration-example-git
    outputs:
    - name: builtImage
      resourceRef:
        name: integration-example-nodefrontend-image
  - name: itest-nodefrontend
    inputs:
    - name: workspace
      resourceRef:
        name: integration-example-git
