apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineRun
metadata:
  name: integration-example-1
spec:
  pipelineRef:
    name: integration-example
  triggerRef:
    type: manual
  serviceAccount: 'default'
  results:
    type: 'gcs'
    url: 'gcs://somebucket/results/logs'
  resources:
  - name: export-npmlib
    inputs:
    - name: workspace
      resourceRef:
        name: integration-example-git
      params:
      - name: directory
        #value: integration-example/nodelib
        # With local git we're only pushing the project folder
        value: nodelib
    outputs:
    - name: builtImage
      resourceRef: 
        name: integration-example-npmlib-image
    params:
    - name: directory
      #value: integration-example/nodelib
      # With local git we're only pushing the project folder
      value: nodelib
