apiVersion: pipeline.knative.dev/v1alpha1
kind: Pipeline
metadata:
  name: integration-example
spec:
  tasks:
  - name: export-npmlib
    taskRef:
      name: npm-export
    params:
    - name: directory
      #value: integration-example/nodelib
      # With local git we're only pushing the project folder
      value: nodelib
